### ISSUE TITLE
Missing some step...

### ISSUE THREAD

**Issue by ZvikaZ** [olegsv/opencart-hebrew-locale#1]
Hi.
Probably it's trivial, but I'm missing the initial step before the instructions you've written.
How do I upload the .zip file?
I tried with Extensions/Installer, but it complaint about the file.
Saw that it requires a ` .ocmod.zip` extension, but changing to it didn't help either.
Probably it needs some specific file hierrarchy inside, but I don't understand what exactly.

**Comment by olegsv** [comment]
@ZvikaZ check opencart version before. If it's compatible, then configure Hebrew locale as described and simply upload contents of /upload folder to your opencart root.
